$(function(){
    $.ajax({
        url:'../../AjaxAjaxServlet',
        type:'POST',
        success:function(data){
            alert(data);
        },
        error:function(data){
            alert(data);
        }
    });
});
